[package]
name = "hello_world"
version = "0.1.0"
edition = "2021"

[dependencies]
plonky2 = "0.1"
plonky2_crypto = "0.1"

[dev-dependencies]
hex = "0.4"

[patch.crates-io]
plonky2_crypto = { path = "../.." }
